name: UnUnbreakable
version: '1.1.0'
main: cn.unUnbreakable.Main
api-version: '1.21'

depend:
  - packetevents

commands:
  ununbreakable:
    description: Main command.
    usage: /<command>

permissions:
  ununbreakable.reload:
    description: Allow the player to reload the plugin.
    default: op
